/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Stream */
        get: operations["live_stream_api_live_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/machine-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Machine Snapshot */
        get: operations["machine_snapshot_api_machine_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the model on a set of inputs and return beam output
         * @description Stateless model evaluation. The one evaluate endpoint for every caller.
         *
         *     Used by this app's own web UI, by any other UI, and by programmatic clients such as
         *     notebooks and emittance GUIs. There is deliberately no separate UI-private endpoint.
         *
         *     `inputs` is a map of PV name -> engineering-unit control value, overlaid on the
         *     model's design baseline, so send only the knobs you want to change (`{}` is the
         *     design machine). `GET /api/config` lists the writable inputs with their ranges and
         *     defaults.
         *
         *     Scalars are always returned. Set `include_image`, `include_distribution` and
         *     `include_twiss` for the heavier outputs, and `max_particles` to subsample the
         *     distribution (it defaults to 3000, never the full beam). Large arrays are
         *     base64-encoded little-endian float32, so decode with e.g.
         *     `numpy.frombuffer(base64.b64decode(s), dtype='<f4')`. The image is row-major,
         *     reshaped to `image.shape`.
         *
         *     Particle positions are in µm and momenta in eV/c, matching the µm-based scalars.
         *     Every response states its own units in `distribution.units`, so do not hard-code
         *     them.
         */
        post: operations["evaluate_v1_api_v1_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Prometheus scrape endpoint. KEDA autoscales the eval pool on lume_pool_inflight.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigResponse */
        ConfigResponse: {
            /** Inputs */
            inputs: components["schemas"]["InputInfo"][];
            /** Model */
            model: string;
            /** Scalars */
            scalars: components["schemas"]["ScalarInfo"][];
            /** Scan Pv */
            scan_pv: string;
            /** Screens */
            screens: components["schemas"]["ScreenInfo"][];
            /** Version */
            version: string;
        };
        /** EvaluateV1Request */
        EvaluateV1Request: {
            /**
             * Include Distribution
             * @default false
             */
            include_distribution: boolean;
            /**
             * Include Image
             * @default false
             */
            include_image: boolean;
            /**
             * Include Twiss
             * @default false
             */
            include_twiss: boolean;
            /**
             * Inputs
             * @default {}
             */
            inputs: {
                [key: string]: number;
            };
            /** Max Particles */
            max_particles?: number | null;
            /** Screen */
            screen: string;
        };
        /** EvaluateV1Response */
        EvaluateV1Response: {
            distribution?: components["schemas"]["V1Distribution"] | null;
            /** Frame Index */
            frame_index: number;
            image?: components["schemas"]["V1Image"] | null;
            /**
             * Image Caption
             * @default
             */
            image_caption: string;
            /**
             * Image Message
             * @default
             */
            image_message: string;
            /** Model */
            model: string;
            scalars: components["schemas"]["Scalars"];
            /** Screen */
            screen: string;
            /** Screen Label */
            screen_label: string;
            /** Timestamp */
            timestamp: number;
            twiss?: components["schemas"]["V1Twiss"] | null;
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InputInfo */
        InputInfo: {
            /** Default */
            default: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Max */
            max: number;
            /** Min */
            min: number;
            /**
             * Unit
             * @default
             */
            unit: string;
        };
        /** ScalarInfo */
        ScalarInfo: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
        };
        /** Scalars */
        Scalars: {
            /** Norm Emit X Um Rad */
            norm_emit_x_um_rad: number;
            /** Norm Emit Y Um Rad */
            norm_emit_y_um_rad: number;
            /** Sigma Z Um */
            sigma_z_um: number;
            /** Xrms Um */
            xrms_um: number;
            /** Yrms Um */
            yrms_um: number;
        };
        /** ScreenInfo */
        ScreenInfo: {
            /** Has Image */
            has_image: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            /** Inputs */
            inputs: {
                [key: string]: number;
            };
        };
        /** V1Distribution */
        V1Distribution: {
            /** Coords */
            coords: {
                [key: string]: string;
            };
            /** N */
            n: number;
            /** Units */
            units: {
                [key: string]: string;
            };
        };
        /** V1Image */
        V1Image: {
            /** Data B64 */
            data_b64: string;
            /**
             * Dtype
             * @default float32
             */
            dtype: string;
            /** Shape */
            shape: number[];
        };
        /** V1Twiss */
        V1Twiss: {
            /** Beta X */
            beta_x: number[];
            /** Beta Y */
            beta_y: number[];
            /** S */
            s: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    live_stream_api_live_stream_get: {
        parameters: {
            query?: {
                screen?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    machine_snapshot_api_machine_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
        };
    };
    evaluate_v1_api_v1_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateV1Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateV1Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
