apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lume-visualizations
resources:
  - namespace.yaml
  - configmap.yaml
  - quad-scan.yaml
  - live-monitor.yaml
  - ingress.yaml
